python3-pip: Add missing dependency [YOCIMX-6184]
Fixes:
```
  File \"/usr/lib/python3.10/site-packages/pip/_vendor/rich/color.py\", line 3, in <module>
    from colorsys import rgb_to_hls
ModuleNotFoundError: No module named 'colorsys'
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>