optee-test: Use the own embedded openssl library [LF-5044]
This is a workaround for the current Optee-test and need be fixed in the feature.

As OpenSSL upgrades to 3.0, some API is deprecated.
optee-test meets build breaks:
   /optee-test/3.15.0.imx-r0/git/host/xtest/regression_8100.c:133:17:
    error: 'ERR_get_error_line' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   133 |                 e = ERR_get_error_line(&f, &l);

Signed-off-by: Jun Zhu <junzhu@nxp.com>