Revert "flatbuffers: Fix build break"
This sequence of commits breaks nnstreamer:

```
ERROR: Multiple versions of flatbuffers are due to be built (sources/meta-ml/recipes-devtools/flatbuffers/flatbuffers_2.0.6.bb sources/meta-openembedded/meta-oe/recipes-devtools/flatbuffers/flatbuffers_2.0.0.bb). Only one version of a given PN should be built in any given build. You likely need to set PREFERRED_VERSION_flatbuffers to select the correct version or don't depend on multiple versions.
```

This reverts commit 5dcf1cca1bdfd019194ef03770bbbd64184468bd.