fsl-imx-preferred-env.inc: Set preferred provider for opencl-headers
opencl-headers recipe has been added in meta-openembedded in thud. This conflicts
with the opencl-headers provided by imx-gpu-viv. So, preferred provider should be set.

This resolves the following error:

ERROR: Multiple .bb files are due to be built which each provide opencl-headers:
/thud/sources/meta-fsl-bsp-release/imx/meta-bsp/recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.2.4.p2.4-aarch64.bb
/thud/sources/meta-openembedded/meta-oe/recipes-core/opencl-headers/opencl-headers_git.bb

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>