qtwayland: Fix xkb and waylandeglclientbufferintegration build error [YOCIMX-1785]
There are two build error in wayland backend.
-qwaylandxkb: error: undefined reference to 'xkb_keysym_to_utf32'
 Enable xkbcommon-evdev for wayland

-Compiling waylandeglclientbufferintegration.cpp ..
 The included file: eglplatform.h: fatal error: X11/Xlib.h: No such file
 Some EGL CFLAGS are missing.
 Add egl to do pkg config to gain "-DLINUX -DEGL_API_FB -DWL_EGL_PLATFORM"
 (The patch will be only added to wayland)

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>