qtwayland: Add a patch to fix build break on sololite
shm-emulation-server is failing on sololite because of its dependency on
opengl
qtwayland/5.10.1+gitAUTOINC+db36bc0d9c-r0/git/src/hardwareintegration/client/shm-emulation-server/shmserverbufferintegration.cpp:81:10:
 error: 'QOpenGLContext' has not been declared
      if (!QOpenGLContext::currentContext())
           ^~~~~~~~~~~~~~

This patch disables shm-emulation-server for sololite

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>