strace: Backport 4.26 recipe from warrior [YOCIMX-3400]
Upgrade to 4.26 via backport.

Fix the following error encountered after moving to libc headers 4.19:

| In file included from ../strace-4.24/static_assert.h:31,
|                  from ../strace-4.24/xlat/v4l2_pix_fmts.h:4,
|                  from ../strace-4.24/v4l2.c:78:
| ../strace-4.24/xlat/v4l2_control_id_bases.h:36:1: error: static assertion failed: "V4L2_CID_USER_IMX_BASE != (V4L2_CID_BASE + 0x1090)"
|  static_assert((V4L2_CID_USER_IMX_BASE) == ((V4L2_CID_BASE + 0x1090)), "V4L2_CID_USER_IMX_BASE != (V4L2_CID_BASE + 0x1090)");
|  ^~~~~~~~~~~~~

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>