xserver-xorg: Remove glamor from packageconfig
There is a conflict with eglvivante.h and fb.h(provided by xorg-xserver)

xserver-xorg/2_1.19.6-r0/recipe-sysroot/usr/include/EGL/eglvivante.h:333:1: error: conflicting types for 'fbDestroyPixmap'
|  fbDestroyPixmap(
|  ^~~~~~~~~~~~~~~
| In file included from ../../xorg-server-1.19.6/glamor/glamor.h:36:0,
|                  from ../../xorg-server-1.19.6/glamor/glamor_priv.h:32,
|                  from ../../xorg-server-1.19.6/glamor/glamor_program.c:23:
| ../../xorg-server-1.19.6/fb/fb.h:1132:2: note: previous declaration of 'fbDestroyPixmap' was here
|   fbDestroyPixmap(PixmapPtr pPixmap);

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>