fsl-imx-preferred-env: Set VIRTUAL-RUNTIME_container_runtime to virtual-runc
VIRTUAL-RUNTIME_container-runtime variable is added which allows switching
betwen runc and crun.

https://git.yoctoproject.org/meta-virtualization/commit/?id=fd0958ed9e38fb5215218ac772230abc2f65c4c2

This fixes the following error:

ERROR: Nothing RPROVIDES '${VIRTUAL-RUNTIME_container_runtime}' (but /home/bamboo/build/6.1-mickledore-full/fsl-imx-internal-xwayland/mx8m/yocto/sources/meta-virtualization/recipes-containers/docker/docker-ce_git.bb, /home/bamboo/build/6.1-mickledore-full/fsl-imx-internal-xwayland/mx8m/yocto/sources/meta-virtualization/recipes-containers/containerd/containerd-opencontainers_git.bb RDEPENDS on or otherwise requires it)
ERROR: Required build target 'test-internal-qt6' has no buildable providers.
Missing or unbuildable dependency chain was: ['test-internal-qt6', 'docker', '${VIRTUAL-RUNTIME_container_runtime}']

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>