tensorflow-lite-vx-delegate: Add back tensorflow-lite-2.8.0 include file
tensorflow-lite-vx-delegate is still on 2.8.0 version and requires tensorflow-lite-2.8.0.inc

Fixes the following error:

ERROR: ParseError at /home/nxa07886/kirkstone/sources/meta-imx/meta-ml/recipes-libraries/tensorflow-lite/
tensorflow-lite-vx-delegate_2.8.0.bb:8: Could not include required file tensorflow-lite-2.8.0.inc

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>