fsl-imx-preferred-env.inc: Enable usrmerge distro feature as it is required by systemd
ERROR: Nothing PROVIDES 'systemd' (but /opt/build/nanbield/sources/meta-openembedded/meta-oe/recipes-bsp/firmwared/firmwared_git.bb, /opt/build/nanbield/sources/meta-imx/meta-bsp/recipes-graphics/wayland/weston_11.0.2.imx.bb, /opt/build/nanbield/sources/poky/meta/recipes-core/psplash/psplash_git.bb DEPENDS on or otherwise requires it)
systemd was skipped: missing required distro feature 'usrmerge' (not in DISTRO_FEATURES)

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>