fsl-imx-base.inc: Remove uninative feature [YOCIMX-4380]
The fixes for YOCIMX-4345 have caused a new issue:

ERROR: When reparsing virtual:native:/home/bamboo/build/5.4-zeus-regression/fsl-imx-internal-xwayland/mx8/temp_build_dir/sources/poky/meta/recipes-bsp/u-boot/u-boot-tools_2019.07.bb:do_populate_sysroot, the basehash value changed from ba1759b5fb2627162513ee6ebb90355179075c6df3ebf6909e9fdab29c79f2b1 to 9965fd6494a9e25c1fc9424838d512e535628d92912c30376602d497d028bcab. The metadata is not deterministic and this needs to be fixed.
ERROR: The following commands may help:
ERROR: $ bitbake u-boot-tools-native -cdo_populate_sysroot -Snone
ERROR: Then:
ERROR: $ bitbake u-boot-tools-native -cdo_populate_sysroot -Sprintdiff

To fix this, the original fixes are now reverted, and we
work around the original problem by removing the uninative
feature.

A new issue YOCIMX-4388 is created to address the underlying
issue so uninative can be restored.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>