audiomanager: Fix build break
package_qa_check_staged is replaced with qa_check_staged in warrior.

This commit fixes the following error:

     0049:# replace function in poky/meta/classes/insane.bbclass
     0050:python do_qa_staging() {
     0051:    bb.note("[workaround] QA checking staging")
     0052:
*** 0053:    if not package_qa_check_staged(d.expand('${SYSROOT_DESTDIR}${STAGING_LIBDIR}'), d):
     0054:        bb.fatal("QA staging was broken by the package built above")
     0055:}
Exception: NameError: name 'package_qa_check_staged' is not defined

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>