qtbase: Fix problem with multiple patches
The following error occurs now for parts with 2D acceleration:

```
ERROR: qtbase-5.15.0+gitAUTOINC+f6fe4bbab7-r0 do_patch: Command Error: 'quilt --quiltrc /home/r60874/zeus/build/tmp/work/aarch64-mx8-poky-linux/qtbase/5.15.0+gitAUTOINC+f6fe4bbab7-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Patch 0014-Add-IMX-GPU-support.patch is already applied; check your series file
```

The problem is that now that the meta-freescale bbappend is
enabled, the same two patches are added for both the imxgpu2d
override and the imxgpu override.

The imxgpu override was added to address parts with 3D but no
2D acceleration. So fix the problem by replacing the imxgpu
override solution with a solution that appends the patches only
in the case of 3D but no 2D acceleration.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>