imx-atf: fsl-eula-unpack shouldn't be inherited [YOCIMX-3447]
ERROR: imx-atf-2.0+gitAUTOINC+c77586be06-r0 do_fetch:
The recipe LICENSE should include Proprietary but is BSD-3-Clause.

"Verify LICENSE contains Proprietary" was newly added into fsl-eula-unpack,
which expose the problem.

imx-atf is built from git directly and it's BSD-3-Clause license,
so it shouldn't inherit fsl-eula-unpack.bbclass.

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>