tensorflow-lite: Add missing OpenCL dependency [LF-12629]
The package does depend on libOpenCL.so at runtime. Fixes:
```
ERROR: TfLiteGpuDelegate Init: Can not open OpenCL library on this device - /usr/lib/libtensorflow-lite.so.2.15.0: undefined symbol: clGetCommandBufferInfoKHR
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>