tensorflow-lite/litert: Add a workaround to fix permissions issue
Exception: KeyError: 'getpwuid(): uid not found: 2000'
Path /home/bamboo/IMXYOCTO-FULL16-MX95-4/yocto/build/tmp/work/armv8a-mx95-poky-linux/litert/1.2.0/sstate-build-package/package/usr/lib/python3.13/
site-packages/ai_edge_litert is owned by uid 2000, gid 2000, which doesn't match any user/group on target. This may be due to host contamination.

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>