Revert "imx-dspc-asrc: Update imx-dspc-asrc_4.4.6.bb to commit ?"
Go back to the original version which is fetched before git owner's rebasing.

Will update the package after error is fixed:
ERROR: imx-dspc-asrc-4.4.6-r0 do_package_qa: QA Issue: /unit_tests/DSPC_ASRC/asrc-test contained
in package imx-dspc-asrc requires lib_dspc_asrc.so()(64bit),
but no providers found in RDEPENDS_imx-dspc-asrc? [file-rdeps]

This reverts commit 989eac4925df22a3ef61c9a11295869327095449.