u-boot-imx: Fix devtool modify u-boot-imx [YOCIMX-8749]
The command `devtool modify u-boot-imx` fails:
```
ERROR: Applying patch '0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch' on target directory '.../u-boot-imx/2024.04/devtooltmp-aet4hqzs/workdir/git'
```

The problem is the patch in `meta-freescale-3rdparty` is out-of-date.
Backport and use the latest file.

https://github.com/Freescale/meta-freescale-3rdparty/blob/18fabd470a447f9ac60ff170e76a78535edfa9be/recipes-bsp/u-boot/u-boot-imx/0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 04f1f31722751671440c1ed0ad471e2ea3abc1f5)