qtwebengine: Force skcms portable for 6 and 7 [YOCIMX-9809]
The build is broken for i.MX 6 and 7 after switching to Qt 6.11:
```
| In file included from ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/skcms_TransformBaseline.cc:47:
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h: In function 'void skcms_private::baseline::run_program(const skcms_private::Op*, const void**, ptrdiff_t, const char*, char*, int, size_t, size_t)':
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:1503:13: error: inlining failed in call to 'always_inline' 'void skcms_private::baseline::exec_stages(void (**)(StageList, const void**, const char*, char*, F, F, F, F, int), const void**, const char*, char*, int)': target specific option mismatch
|  1503 |     SI void exec_stages(StageFn* stages, const void** contexts, const char* src, char* dst, int i) {
|       |             ^~~~~~~~~~~
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:1556:20: note: called from here
|  1556 |         exec_stages(stages, contexts, src, dst, i);
|       |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:1503:13: error: inlining failed in call to 'always_inline' 'void skcms_private::baseline::exec_stages(void (**)(StageList, const void**, const char*, char*, F, F, F, F, int), const void**, const char*, char*, int)': target specific option mismatch
|  1503 |     SI void exec_stages(StageFn* stages, const void** contexts, const char* src, char* dst, int i) {
|       |             ^~~~~~~~~~~
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:1564:20: note: called from here
|  1564 |         exec_stages(stages, contexts, tmp, tmp, 0);
|       |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:1503:13: error: inlining failed in call to 'always_inline' 'void skcms_private::baseline::exec_stages(void (**)(StageList, const void**, const char*, char*, F, F, F, F, int), const void**, const char*, char*, int)': target specific option mismatch
|  1503 |     SI void exec_stages(StageFn* stages, const void** contexts, const char* src, char* dst, int i) {
|       |             ^~~~~~~~~~~
| ../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/skia/modules/skcms/src/Transform_inl.h:1564:20: note: called from here
|  1564 |         exec_stages(stages, contexts, tmp, tmp, 0);
|       |         ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The problem is a classic "target specific option mismatch" that pops up
when a function that was compiled with one set of CPU features (e.g.,
AVX/NEON/SVE) gets inlined into a caller compiled without those same
features.

Force skcms scalar baseline (no NEON/FP16 in Transform_inl.h)
to fix.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>