layer.conf: Fix multiple runtime providers for u-boot-default-env
Now that we prefer u-boot-imx-mfgtool over u-boot-fslc-mfgtool, it seems that we have
two runtime providers for u-boot-default-env, set in poky u-boot.inc.

```
ERROR: Trying to resolve runtime dependency u-boot-default-env resulted in conflicting PREFERRED_PROVIDER entries being found.
The providers found were: ['/home/bamboo/build/5.10-gg-core/fsl-imx-internal-wayland/mx6/temp_build_dir/sources/meta-imx/meta-bsp/recipes-bsp/u-boot/u-boot-imx-mfgtool_2020.04.bb', '/home/bamboo/build/5.10-gg-core/fsl-imx-internal-wayland/mx6/temp_build_dir/sources/meta-imx/meta-bsp/recipes-bsp/u-boot/u-boot-imx_2020.04.bb']
The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_u-boot-mfgtool = u-boot-imx-mfgtool', 'PREFERRED_PROVIDER_virtual/bootloader = u-boot-imx']. You could set PREFERRED_RPROVIDER_u-boot-default-env
```

Fix the problem so we choose u-boot-imx.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>