imx-gpu-sdk: Disable vulkan for Wayland [YOCIMX-2417]
Disable vulkan configuration on Wayland due to build break:

ERROR: Could not locate the content builder 'glslangValidator' (Vulkan shader compiler used to convert GLSL/HLSL shaders to binary SPIR-V files)

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>