imx-gpu-viv: Include gl31.h for 8MP [YOCIMX-4169]
The GPU drivers install for 8MP was missing gl31.h, which was
causing a build break for imx-gpu-sdk:

| In file included from source/FslUtil/OpenGLES3_1/GLShaderProgram.cpp:35:
| include/FslUtil/OpenGLES3_1/GLShaderProgram.hpp:37:10: fatal error: GLES3/gl31.h: No such file or directory
|    37 | #include <GLES3/gl31.h>
|       |          ^~~~~~~~~~~~~~
| compilation terminated.
| GNUmakefile_Yocto:115: recipe for target 'build/Yocto/obj/Release/source/FslUtil/OpenGLES3_1/GLShaderProgram.o' failed

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>