tensorflow-lite: Patch build break for ethosu.h
The header ethosu.h is located in /usr/include/linux.

Fixes:
```
| tensorflow/lite/kernels/ethos_u/ethosu_drv.cc:20:10: fatal error: ethosu.h: No such file or directory
|    20 | #include <ethosu.h>
|       |          ^~~~~~~~~~
| compilation terminated.
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit b71b78f2c5e34925d2d532d89c6237ffe020dfe2)