Revert "flatbuffers: recipe fix"
This sequence of commits breaks nnstreamer:

```
ERROR: Multiple versions of flatbuffers are due to be built (sources/meta-ml/recipes-devtools/flatbuffers/flatbuffers_2.0.6.bb sources/meta-openembedded/meta-oe/recipes-devtools/flatbuffe>
```

This reverts commit a24e858ce4b96c41e69798b81ff398bee5fc19a9.