freerdp: Backport v2.4.1 from meta-oe master branch [LF-5044]
As OpenSSL is upgraded to 3.0.0, freerdp v2.3.1 meets the build break:

	<<PKGBUILDDIR>>/winpr/libwinpr/utils/ssl.c:249:8: warning: implicit
	declaration of function â€˜FIPS_mode_setâ€™ [-Wimplicit-function-declaration]
	249 |    if (FIPS_mode_set(1))
	    |        ^~~~~~~~~~~~
	/usr/bin/ld: ../../libwinpr/libwinpr2.so.2.3.0: undefined reference to `FIPS_mode_set'
	/usr/bin/ld: ../../libwinpr/libwinpr2.so.2.3.0: undefined reference to `FIPS_mode'
	collect2: error: ld returned 1 exit status

Signed-off-by: Jun Zhu <junzhu@nxp.com>