imx-uuc: Ignore no configure script error [YOCIMX-8816]
The do_configure task is failing:
```
ERROR: imx-uuc-0.5.1+git-r1 do_configure: no configure script found at ./configure
```

It appears to be due to this OE-Core change:

    autotools: require that a configure script exists

    There's no point inheriting autotools if you're not actually going to
    run a configure script, so make a missing configure script fatal.

https://github.com/openembedded/openembedded-core/commit/6d327a39befae44a88a812bdf4acde800dcee57b

Workaround the problem for now by overriding do_configure.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>