chromium-ozone-wayland: Add a temporary workaround for missing arch speciifc libclang_rt.builtins.a
Building the upstream chromium 140 PR broke with the following error and this change fixes it.

https://github.com/OSSystems/meta-browser/pull/923

ERROR: chromium-ozone-wayland-140.0.7339.136-r0 do_compile: Execution of '/home/chromium/whinlatter/bld-mx8/tmp/work/armv8a-mx8-poky-linux/chromium-ozone-wayland/140.0.7339.136/temp/run.do_compile.547038' failed with exit code 1
ERROR: Logfile of failure stored in: /home/chromium/whinlatter/bld-mx8/tmp/work/armv8a-mx8-poky-linux/chromium-ozone-wayland/140.0.7339.136/temp/log.do_compile.547038
Log data follows:
| DEBUG: Executing shell function do_compile
| ninja: error: '../../../../recipe-sysroot-native/usr/lib/clang/latest/lib/aarch64-unknown-linux-gnu/libclang_rt.builtins.a', needed by 'obj/build/rust/allocator/liballoc_error_handler_impl.a', missing and no known rule to make it
| WARNING: exit code 1 from a shell command.

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>