jsoncpp-nlohmann: Upgrade to 3.10.2 [YOCIMX-5695]
The 3.9.1 version has a build break on gcc 11.2, used by honister.

```
/.../git/test/thirdparty/doctest/doctest.h:4021:47: error: size of array 'altStackMem' is not an integral constant-expression
 4021 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
```

The latest release does not have this problem and is compatible with
imx-gpu-sdk 5.8.0.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>