assimp: Upgrade to 4.1.0 [STDIO-510]
The downported recipe from master has a build failure:

ERROR: assimp-4.1.0-r0 do_package: QA Issue: assimp: Files/directories were installed but not shipped in any package:
  /usr/lib/cmake
  /usr/lib/cmake/assimp-4.1
  /usr/lib/cmake/assimp-4.1/assimp-config.cmake
  /usr/lib/cmake/assimp-4.1/assimp-config-version.cmake

The fix for this issue was in the 4.0.0 recipe but removed
from the 4.1.0 recipe for some unknown reason.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>