imx-gpu-viv: Limit dependency on kernel-module-imx-gpu-viv [YOCIMX-5972]
Trying to build multilib can result in a strange error due to multiple
providers of kernel-module-imx-gpu-viv even though kernel-module-imx-gpu-viv
is not configured:

```
ERROR: Trying to resolve runtime dependency kernel-module-imx-gpu-viv resulted in conflicting PREFERRED_PROVIDER entries being found.
The providers found were: ['virtual:multilib:lib32:/.../sources/meta-imx/meta-bsp/recipes-kernel/linux/linux-imx-mfgtool_5.15.bb', '/.../sources/meta-imx/meta-bsp/recipes-kernel/linux/linux-imx-mfgtool_5.15.bb']
The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_lib32-linux-imx-mfgtool = lib32-linux-imx-mfgtool', 'PREFERRED_PROVIDER_linux-imx-mfgtool = linux-imx-mfgtool']. You could set PREFERRED_RPROVIDER_kernel-module-imx-gpu-viv
NOTE: Multiple providers are available for runtime kernel-module-imx-gpu-viv (linux-imx-mfgtool, lib32-linux-imx-mfgtool, kernel-module-imx-gpu-viv, linux-imx)
Consider defining a PREFERRED_RPROVIDER entry to match kernel-module-imx-gpu-viv
NOTE: Runtime target 'kernel-module-imx-gpu-viv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kernel-module-imx-gpu-viv']
NOTE: Runtime target 'weston-xwayland' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['weston-xwayland', 'virtual/egl', 'kernel-module-imx-gpu-viv']
ERROR: Required build target 'imx-image-core' has no buildable providers.
Missing or unbuildable dependency chain was: ['imx-image-core', 'weston-xwayland', 'virtual/egl', 'kernel-module-imx-gpu-viv']
```

Rework the implementation so that kernel-module-imx-gpu-viv is marked
as a dependency only when it is configured. Also move the dependency to
the machine level to avoid making imx-gpu-viv machine-specific.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>