libcamera: Fix multilib install [LF-16861]
The multilib install is incorrect and generates the QA error:
```
ERROR: libcamera-1_0.5.2.imx-r0 do_package: QA Issue: libcamera: Files/directories were installed but not shipped in any package:
  /usr/lib/python3.13/site-packages/libcamera/_libcamera.so
  /usr/lib/python3.13/site-packages/libcamera/__init__.py
  /usr/lib/python3.13/site-packages/libcamera/__pycache__
  /usr/lib/python3.13/site-packages/libcamera/__pycache__/__init__.cpython-313.pyc
```

It seems this is a troublesome area, and the current problem arises due
to this update:
https://github.com/libcamera-org/libcamera/commit/d54e5537ca0909339bb6950f3a565c9077406a3c

Fix the issue (for now) by following the advice of the update to
override python.platlibdir.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>