Revert "linux-firmware_git.bbappend: Get CYW43XX firmware from imx-firmware.git [YOCIMX-3258]"
Revert it until the build break is fixed. Need more work on firmware-imx recipe.

Error: Transaction check error:
  file /etc/firmware/BCM4335C0.ZP.hcd conflicts between attempted installs of firmware-imx-brcm-1:8.2-r0.noarch
and linux-firmware-bcm4339-1:0.0+git0+1baa34868b_a0026b646c+c9f90affe8-r0.noarch

This reverts commit 0ebada1af4f3b1de0f1ae9baacb45d0464618dc3.