optee-client: Silence _FORTIFY_SOURCE warning [TEE-496]
Re-aligning with poky.conf has introduced some more strict
security checks, triggering the following build break:

| In file included from /home/r60874/zeus/build/tmp/work/aarch64-poky-linux/optee-client/3.2.0.imx-r0/recipe-sysroot/usr/include/bits/libc-header-start.h:33,
|                  from
| /home/r60874/zeus/build/tmp/work/aarch64-poky-linux/optee-client/3.2.0.imx-r0/recipe-sysroot/usr/include/stdio.h:27,
|                  from src/teec_trace.c:27:
| /home/r60874/zeus/build/tmp/work/aarch64-poky-linux/optee-client/3.2.0.imx-r0/recipe-sysroot/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
|   382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|       |    ^~~~~~~

Fix the problem with the qoriq solution, which is to
silence the warning.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>