weston: Remove RECIPE_SYSROOT override [YOCIMX-2603]
The override was needed when the weston 2.0 recipe was
downported to morty. Now that we are on rocko, setting the
variable is at best un-necessary. At worst, it may have been
causing an incremental build break:

ERROR: weston-4.0.0-r0 do_populate_sysroot_setscene: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:extend_recipe_sysroot(d)
     0003:
File: '/home/bamboo/build/4.9-rocko_mx8/fsl-imx-internal-xwayland/temp_build_dir/sources/poky/meta/classes/staging.bbclass', lineno: 565, function: extend_recipe_sysroot
     0561:                    dest = newmanifest[l]
     0562:                    if l.endswith("/"):
     0563:                        staging_copydir(l, targetdir, dest, seendirs)
     0564:                        continue
 *** 0565:                    staging_copyfile(l, targetdir, dest, postinsts, seendirs)
     0566:
     0567:    bb.note("Installed into sysroot: %s" % str(msg_adding))
     0568:    bb.note("Skipping as already exists in sysroot: %s" % str(msg_exists))
     0569:
File: '/home/bamboo/build/4.9-rocko_mx8/fsl-imx-internal-xwayland/temp_build_dir/sources/poky/meta/classes/staging.bbclass', lineno: 151, function: staging_copyfile
     0147:        os.symlink(linkto, dest)
     0148:        #bb.warn(c)
     0149:    else:
     0150:        try:
 *** 0151:            os.link(c, dest)
     0152:        except OSError as err:
     0153:            if err.errno == errno.EXDEV:
     0154:                bb.utils.copyfile(c, dest)
     0155:            else:
Exception: FileExistsError: [Errno 17] File exists: '/home/bamboo/build/4.9-rocko_mx8/fsl-imx-internal-xwayland/temp_build_dir/build_fsl-imx-internal-xwayland/tmp/sysroots-components/aarch64/base-passwd/sysroot-providers/base-passwd' -> '/home/bamboo/build/4.9-rocko_mx8/fsl-imx-internal-xwayland/temp_build_dir/build_fsl-imx-internal-xwayland/tmp/sysroots/imx8qmmek/sysroot-providers/base-passwd'

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>