imx-gpu-viv: Fix EGL backwards compatibility on framebuffer [MGS-6394]
The EGL platform API has changed, breaking existing code. Update eglplatform.h
so the old API is supported as well. Fixes:

```
.../DemoFramework/FslNativeWindow/EGL/source/FslNativeWindow/EGL/FB/EGLNativeWindowSystemFB.cpp:63:25: error: invalid 'static_cast' from type 'void*' to type 'EGLNativeWindowType' {aka 'long unsigned int'}
   63 |         fbDestroyWindow(static_cast<EGLNativeWindowType>(pWindow));
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>