linuxptp: Fix unknown type name 'clockid_t' [YOCIMX-3401]
Error:
linuxptp/1.8-r0/recipe-sysroot/usr/include/linux/net_tstamp.h:158:2: error: unknown type name 'clockid_t'
|   clockid_t clockid; /* reference clockid */
|   ^~~~~~~~~
| In file included from clock.c:20:

net_tstamp.h in recent kernel versions requires time.h for clockid_t.

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>