opencv: Use the protobuf from opencv source to fix dnn error [MGS-6414]
Using protobuf from meta-oe caused the build break. Use it from opencv source instead.

/home/bamboo/build/5.10-honister-full/fsl-imx-internal-xwayland/mx8/yocto/build/tmp/work/cortexa72-cortexa53-crypto-mx8-poky-linux/opencv/4.5.2.imx-r0/git
/modules/dnn/src/caffe/caffe_io.cpp:1114:35: error: no matching function for call
to 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit(const int&, int)'

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>