opencv: Fix path for numpy [YOCIMX-8734]
On walnascar, a numpy include path change causes a build break:
```
modules/python/src2/cv2.hpp:39:10: fatal error: numpy/ndarrayobject.h: No such file or directory
   39 | #include <numpy/ndarrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>