u-boot-imx: Exclude meta-freescale-3rdparty bbappend [YOCIMX-9248]
The command `devtool modify u-boot-imx` fails because of a patch in
meta-freescale-3rdparty:
```
ERROR: Applying patch '0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch' on target directory '/.../tmp/work/imx943_19x19_lpddr4_evk-poky-linux/u-boot-imx/2025.04/devtooltmp-2kb8sbhi/workdir/git'
BBHandledException("Applying '0001-Add-Olimex-iMX8MP-SOM-EVB-IND.patch' failed:
stdout: checking file arch/arm/dts/Makefile
Hunk #1 FAILED at 1168.
1 out of 1 hunk FAILED
checking file arch/arm/dts/imx8mp-olimex.dts
checking file arch/arm/mach-imx/imx8m/Kconfig
Hunk #1 succeeded at 500 (offset 54 lines).
Hunk #2 FAILED at 492.
1 out of 2 hunks FAILED
```

The patch is not needed, so ignore the bbappend.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>