vulkan-samples: Use latest source
A patch added upstream could not be applied.
```
ERROR: vulkan-samples-git-r0 do_patch: QA Issue: Fuzz detected:
```

This error uncovers a deeper problem, that the source is locked on an
old version, and the reason for the lock is no longer valid.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>