python3-pillow: Disable ptest when x11 is not supported
The machine learning package torchvision can no longer be built without
x11 in distro features:
```
ERROR: Nothing RPROVIDES 'tk' (but meta-openembedded/meta-python/recipes-devtools/python/python3-pillow_9.4.0.bb RDEPENDS on or otherwise requires it)
tk was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
Missing or unbuildable dependency chain was: ['packagegroup-imx-ml', 'torchvision', 'python3-pillow', 'tk']
```

The problem started when ptest support was added to python3-pillow
recipe [1].

[1] https://github.com/openembedded/meta-openembedded/commit/7b0e71e00ce1b003c96ef38ead72a9e02555afbe

Fix the problem by making the ptest enablement conditional on x11
support.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>