imx-gpu-viv: Restore virtual/opencl-icd to PROVIDES
Since opencv depends on virtual/opencl-icd, restore virtual/opencl-icd to the
recipes provided so imx-gpu-viv is properly selected. Fixes:

```
ERROR: Multiple versions of imx-gpu-viv are due to be built (/home/r60874/gatesgarth/sources/meta-imx/meta-bsp/recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.3.p1.6-aarch64.bb /home/r60874/gatesgarth/sources/meta-freescale/recipes-graphics/imx-gpu-viv/imx-gpu-viv_6.4.3.p0.0-aarch64.bb). Only one version of a given PN should be built in any given build. You likely need to set PREFERRED_VERSION_imx-gpu-viv to select the correct version or don't depend on multiple versions.
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>