imx-gpu-viv: Suppress libgl runtime dependency error [MGS-5778]
The following QA error is reported when building on Wayland
backend with no XWayland support:

```
ERROR: imx-gpu-viv-1_6.4.0.p2.6-aarch32-r0 do_package_qa: QA Issue: /usr/lib/libGL.so.1.2.0 contained in package libgl-imx requires libXdamage.so.1, but no providers found in RDEPENDS_libgl-imx? [file-rdeps]
ERROR: imx-gpu-viv-1_6.4.0.p2.6-aarch32-r0 do_package_qa: QA Issue: /usr/lib/libGL.so.1.2.0 contained in package libgl-imx requires libXfixes.so.3, but no providers found in RDEPENDS_libgl-imx? [file-rdeps]
ERROR: imx-gpu-viv-1_6.4.0.p2.6-aarch32-r0 do_package_qa: QA Issue: /usr/lib/libGL.so.1.2.0 contained in package libgl-imx requires libXext.so.6, but no providers found in RDEPENDS_libgl-imx? [file-rdeps]
ERROR: imx-gpu-viv-1_6.4.0.p2.6-aarch32-r0 do_package_qa: QA Issue: /usr/lib/libGL.so.1.2.0 contained in package libgl-imx requires libX11.so.6, but no providers found in RDEPENDS_libgl-imx? [file-rdeps]
ERROR: imx-gpu-viv-1_6.4.0.p2.6-aarch32-r0 do_package_qa: QA Issue: /usr/lib/libGL.so.1.2.0 contained in package libgl-imx requires libdrm.so.2, but no providers found in RDEPENDS_libgl-imx? [file-rdeps]
ERROR: imx-gpu-viv-1_6.4.0.p2.6-aarch32-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
```

This needs to be fixed, but for now suppress the error and make
it a runtime problem.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>