ivi: Remove vsomeip from installation
Doesn't build with zeus, probably because of boost being upgraded.
ERROR:
  [...]/reactive_socket_service_ext.hpp:29:10: fatal error: \
    boost/asio/detail/addressof.hpp: No such file or directory

Signed-off-by: Mihai Lindner <mihai.lindner@nxp.com>