nxp-wlan-sdk_git.inc: Fix missing RDEPENDS on wireless-tools
Building without meta-imx/meta-sdk layer reveals that nxp-wlan-sdk and
kernel-module-nxp89xx have a runtime dependency on wireless-tools.

```
ERROR: Nothing RPROVIDES 'wireless-tools' (but
    /.../meta-imx/meta-bsp/recipes-connectivity/nxp-wlan-sdk/nxp-wlan-sdk_git.bb,
    /.../meta-imx/meta-bsp/recipes-kernel/kernel-modules/kernel-module-nxp89xx.bb
    RDEPENDS on or otherwise requires it)
```

Update the RRECOMMENDS to RDEPENDS.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>