imx-gpu-sdk: Remove rapidvulkan fron RDEPENDS for imx8mmevk
rapidvulkan depends on the vulkan-headers which is not supported on imx8mmevk.
This fixes the following error:

ERROR: Nothing PROVIDES 'vulkan-headers' (but /home/bamboo/build/5.4-zeus-regression/fsl-imx-internal-xwayland/mx8m/temp_build_dir/
sources/meta-imx/meta-sdk/recipes-graphics/rapidvulkan/rapidvulkan_1.2.141.2001.bb DEPENDS on or otherwise requires it)
vulkan-headers was skipped: incompatible with machine imx8mmevk (not in COMPATIBLE_MACHINE)

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>