isp-imx: Work-around file-rdeps QA error [YOCIMX-8318]
Fix the QA error:
ERROR: isp-imx-4.2.2.24.3-r0 do_package_qa:
- QA Issue: /usr/lib/libmedia_server.so contained in package isp-imx requires libjsoncpp.so.25()(64bit), but no providers found in RDEPENDS:isp-imx? [file-rdeps]
- QA Issue: /opt/imx8-isp/bin/tuningext contained in package isp-imx requires libjsoncpp.so.25()(64bit), but no providers found in RDEPENDS:isp-imx? [file-rdeps]
- QA Issue: /opt/imx8-isp/bin/isp_media_server contained in package isp-imx requires libjsoncpp.so.25()(64bit), but no providers found in RDEPENDS:isp-imx? [file-rdeps]

Signed-off-by: Jun Zhu <junzhu@nxp.com>