pytorch: Fix do_package_qa error
pytorch v1.7.1 release only support GCC 10.X.
Although the GCC and glibc versions are different, the pytorch should work.
So update the pytorch recipe to ignore the file-rdeps issue.

This commit fixes the following error:

ERROR: pytorch-1.7.1-r0 do_package_qa: QA Issue: /usr/lib/python3.7/site-packages/torch/lib/libtorch_python.so
contained in package pytorch requires libc.so.6(GLIBC_2.32)(64bit), but no providers found in RDEPENDS_pytorch? [file-rdeps]

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>