nn-imx: Library versions got added in nn-imx build-out libraries
This fixes the onnxruntime build:

build_fsl-imx-xwayland/tmp/work/aarch64-poky-linux/onnxruntime/1.1.2-r0/recipe-sysroot/usr/lib/libnnrt.so: undefined reference to `vsi_nn_CreateContext'

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>