imx-image-full: Remove packagegroup-security-parsec due to build break [LF-14936]
Avoid the build break for parsec-service.

```
ERROR: Logfile of failure stored in: /home/bamboo/build/walnascar/Linux_IMX_Full/fsl-imx-internal-xwayland/mx9/yocto/build/tmp/work/armv8a-poky-linux/parsec-service/1.4.1/temp/log.do_compile.1038884
| DEBUG: Executing shell function do_compile
| NOTE: Using rust targets from /home/bamboo/build/walnascar/Linux_IMX_Full/fsl-imx-internal-xwayland/mx9/yocto/build/tmp/work/armv8a-poky-linux/parsec-service/1.4.1/rust-targets/
| NOTE: cargo = /home/bamboo/build/walnascar/Linux_IMX_Full/fsl-imx-internal-xwayland/mx9/yocto/build/tmp/work/armv8a-poky-linux/parsec-service/1.4.1/recipe-sysroot-native/usr/bin/cargo
| NOTE: cargo build -v --frozen --target aarch64-poky-linux-gnu --release --manifest-path=/home/bamboo/build/walnascar/Linux_IMX_Full/fsl-imx-internal-xwayland/mx9/yocto/build/tmp/work/armv8a-poky-linux/parsec-service/1.4.1/parsec-service-1.4.1//Cargo.toml  --features mbed-crypto-provider,pkcs11-provider,cryptoki/generate-bindings
| WARNING: exit code 1 from a shell command.
| error: unexpected argument 'mbed-crypto-provider' found
|
| Usage: cargo build [OPTIONS]
|
| For more information, try '--help'.
NOTE: recipe parsec-service-1.4.1-r0: task do_compile: Failed
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>