fsl-setup-release.sh: Enable meta-rust layer as meta-browser depends on it.
This fixes the following error:

ERROR: Layer 'browser-layer' depends on layer 'rust-layer', but this layer is not
enabled in your configuration

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>