imx-gpu-viv: Drop vulkan headers
The build is broken due to a duplicated Vulkan header:

```
ERROR: qtbase-6.3.2-r0 do_prepare_recipe_sysroot: The file /usr/include/vulkan/vulkan_directfb.h is installed by both vulkan-headers and imx-gpu-viv, aborting
```

Remove the Vulkan headers installed from the GPU archive.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>