layer.conf: Remove upstream SDMA linux-firmware
This fixes the following error:

ERROR: Nothing RPROVIDES 'linux-firmware-imx-sdma-imx7d' (but /home/bamboo/build/5.4-gg-full/fsl-imx-internal-xwayland/mx8/temp_build_dir/sources/poky/meta/recipes-core/packagegroups/packagegroup-base.bb RDEPENDS on or otherwise requires it)
ERROR: Required build target 'imx-image-core' has no buildable providers.
Missing or unbuildable dependency chain was: ['imx-image-core', 'packagegroup-base-extended', 'linux-firmware-imx-sdma-imx7d']

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>