Revert "armnn: Add pyarmnn examples, unit tests, whl, and remove mobilenet v1 model [YOCIMX-5262]"
This does not build:

```
AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'linux_aarch64')
```

This reverts commit 7f4d716df10c63c2c33125f14b92a3a01d1badd6.