layer.conf: Remove image install setting for xen
Fix:
ERROR: Nothing RPROVIDES 'imx-xen-base' (but /home/bamboo/build/zeus-5.10-lf/fsl-imx-internal-xwayland/mx8/temp_build_dir/sources/meta-fsl-mpu-internal/bsp-internal/dynamic-layers/qt5-layer/recipes-fsl/images/test-internal-qt5.bb RDEPENDS on or otherwise requires it)
ERROR: Required build target 'test-internal-qt5' has no buildable providers.
Missing or unbuildable dependency chain was: ['test-internal-qt5', 'imx-xen-base']

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>