imx-test: Fix termio.h replaced by termios.h
error:
| mxc_uart_test/mxc_uart_xmit_test.c:21:10: fatal error: termio.h: No such file or directory

Signed-off-by: Zelan Zou <zelan.zou@nxp.com>