packagegroup-fsl-tools-audio: Remove imx-dspc-asrc since it is broken [YOCIMX-3457]
ERROR: imx-dspc-asrc-4.4.6-r0 do_package_qa: QA Issue: /unit_tests/DSPC_ASRC/asrc-test contained in package imx-dspc-asrc requires lib_dspc_asrc.so()(64bit), but no providers found in RDEPENDS_imx-dspc-asrc? [file-rdeps]

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>