gstreamer1.0-plugins-bad-qt: Fix QA error in rocko [YOCIMX-2223]
ERROR: gstreamer1.0-plugins-bad-qt-1.12.2-r0 do_package_qa:
QA Issue: /usr/lib/gstreamer-1.0/libgstqmlgl.so contained in
package gstreamer1.0-plugins-bad-qt-qmlgl requires libgstgl-1.0.so.0()(64bit),
but no providers found in RDEPENDS_gstreamer1.0-plugins-bad-qt-qmlgl? [file-rdeps]

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>