vulkan-demos: Set SRCREV_FORMAT variable as multiple SCMs are used
This fixes the following error:

File "/opt/build/nanbield/sources/poky/bitbake/lib/bb/fetch2/__init__.py", line 804, in _get_srcrev(d=<bb.data_smart.DataSmart object         at 0x7f1285adc8b0>, method_name='sortable_revision'):
         if not format:
    >        raise FetchError("The SRCREV_FORMAT variable must be set when multiple SCMs are used.\n"\
                              "The SCMs are:\n%s" % '\n'.join(scms))
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue        (d)} which triggered exception FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used.
The SCMs are:
git://github.com/SaschaWillems/Vulkan.git;protocol=https;branch=master
git://github.com/g-truc/glm;destsuffix=git/external/glm;name=glm;protocol=https;branch=master
git://github.com/KhronosGroup/KTX-Software;destsuffix=git/external/ktx;name=ktx;lfs=0;protocol=https;branch=master
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>