imx-gpu-apitrace: Fix configuration problem [YOCIMX-2885]
The X11 configuration changed, resulting in an improper configuration
detected by package content validation.

+ bitbake imx-gpu-apitrace
ERROR: imx-gpu-apitrace-7.1.0-r0 do_install_validate: imx-gpu-apitrace: Install validation failed for package
at /home/bamboo/automation/trunk_pkg_sumo/graphics_pkg_64/temp_build_dir/build-graphics-aarch64-wayland/tmp/work/aarch64-mx8-poky-linux/imx-gpu-apitrace/7.1.0-r0/image
The following files were added to the package:
  ./usr/bin/glretrace
  ./usr/lib/apitrace/wrappers/glxtrace.so

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>