fsl-imx-preferred-env: Set PREFERRED_VERSION of libdrm to 2.4.91.imx [YOCIMX-3290]
In thud, poky has libdrm v2.4.94, and meta-freescale has libdrm v2.4.91.imx.
Set version to 2.4.91.imx or it will automatically use newest one, which has
build break:
ERROR: libdrm-2.4.94-r0 do_fetch:
Fetcher failure for URL: 'file://drm-update-arm.patch'.
Unable to fetch URL from any source.
(The v2.4.94 bb file in poky and bbappend file in meta-freescale together cause the error)

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>