qtwayland: Fix tst_client build error in imx6slevk with no-opengl [YOCIMX-2509]
imx6slevk has no-opengl, and there is tst_client build error with no-opengl,
Error: tst_client: error: 'QOpenGLWindow' has not been declared...

The error is introduced by qtwayland patch: bf09c7a1493c01a65ee0f110b37a04e653edc08e

Add QT_NO_OPENGL check.

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>