Revert "imx-vpu-hantro: Change depends to linux-imx-headers from kernel"
This change cannot be made because the package depends on another header
in the kernel:

decoder_sw/software/linux/dwl/dwl_linux.c:42:10: fatal error: linux/hantrodec.h: No such file or directory

This reverts commit a1cb37c10227ef0d4abc688ddea31a18eed50617.