fsl-imx-base.inc: Fix fetcher failure for Qt 5.15.2 [YOCIMX-6895]
The Qt bugfix branches are removed, so the meta-qt5 recipes are broken:
```
ERROR: qtbase-5.15.2+gitAUTOINC+40143c189b-r0 do_fetch: Fetcher failure: Unable to find revision 40143c189b7c1bf3c2058b77d00ea5c4e3be8b28 in branch 5.15.2 even from upstream
ERROR: qtbase-5.15.2+gitAUTOINC+40143c189b-r0 do_fetch: Fetcher failure for URL: 'git://code.qt.io/qt/qtbase.git;name=qtbase;branch=5.15.2;protocol=git'. Unable to fetch URL from any source.
```

Fix the problem by disabling branch checking.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 4bba4a5dc980ba523470d0bfe3b186fa4fb60c17)
(cherry picked from commit 60905dc94d0270f1a66e41fd5e051e4839199d8c)
(cherry picked from commit d176aee3567cdccb5a7fb7c7e70a7cb3bee51bc0)