nnshark: Fix PACKAGE_ARCH
The recipe does try to install the same licenses as gst-shark, causing
the failure:
```
ERROR: gst-shark-0.7.3.1-r0 do_create_spdx_setscene: Recipe gst-shark is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  .../tmp/deploy/spdx/by-namespace/armv8a/http:__spdx.org_spdxdoc_libgstshark-dev-00c7fe55-eba2-5b20-86e7-e6050ecbfd56
    (matched in manifest-armv8a-nnshark.create_spdx)
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>