Revert "tensorflow-lite: Obsolete flatbuffers dependency removal"
This sequence of commits breaks nnstreamer:

```
ERROR: Multiple versions of flatbuffers are due to be built (sources/meta-ml/recipes-devtools/flatbuffers/flatbuffers_2.0.6.bb sources/meta-openembedded/meta-oe/recipes-devtools/flatbuffe>
```

This reverts commit e21614310a06cbaa9f0362571a91ab29b64501d7.