vulkan: Use version 1.3.275.0.imx for GPU and non-GPU
OE-Core vulkan is upgraded to 1.4.309.0, which breaks our layer:
```
ERROR: No recipes in default available for:
  meta-imx/meta-imx-bsp/recipes-graphics/vulkan/vulkan-loader_1.3.296.0.bbappend
```

Fix the problem by adjusting the non-GPU configuration to use the same
version as for GPU.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>