layer.conf: Set CONNECTIVITY_URIS to a reliable location [YOCIMX-6365]
Backport OE-Core solution dc6b043 to fix:
```
ERROR: OE-core's config sanity checker detected a potential misconfiguration.
Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
Following is the list of potential problems / advisories:

Fetcher failure for URL: 'https://www.example.com/'. URL https://www.example.com/ doesn't work.
Please ensure your host's network is configured correctly.
If your ISP or network is blocking the above URL,
try with another domain name, for example by setting:
CONNECTIVITY_CHECK_URIS = "https://www.yoctoproject.org/" You could also set BB_NO_NETWORK = "1" to disable network
access if all required sources are on local disk.
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>