imx-g2d-samples: Add missing Wayland dependency [YOCIMX-6581]
Fixes:
```
| ../os/linux/wayland/xdg-shell-protocol.c:33:10: fatal error: wayland-util.h: No such file or directory
|    33 | #include "wayland-util.h"
|       |          ^~~~~~~~~~~~~~~~
| g2d_wayland_cf.c:20:10: fatal error: wayland-client-protocol.h: No such file or directory
|    20 | #include <wayland-client-protocol.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>