imx-gpu-viv: Include gl31.h for 8M Nano [YOCIMX-3777]
The GPU drivers install for 8M Nano was missing gl31.h, which was
causing a build break for imx-gpu-sdk:

| In file included from source/FslUtil/OpenGLES3_1/GLProgramPipeline.cpp:35:
| include/FslUtil/OpenGLES3_1/GLProgramPipeline.hpp:37:10: fatal error: GLES3/gl31.h: No such file or directory
|  #include <GLES3/gl31.h>
|           ^~~~~~~~~~~~~~

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>