v4l-utils: Drop virtual/libgl dependency [YOCIMX-5642]
The imx-gpu-viv recipe is cleaned up, such that an incorrect claim to
provide GL on framebuffer is no longer made. Without this claim, v4l-utils
does now fail to build because it has just such a dependency:

```
ERROR: Nothing PROVIDES 'virtual/libgl' (but sources/meta-openembedded/meta-oe/recipes-multimedia/v4l2apps/v4l-utils_1.20.0.bb DEPENDS on or otherwise requires it)
mesa-gl PROVIDES virtual/libgl but was skipped: incompatible with machine imx6qpdlsolox (not in COMPATIBLE_MACHINE)
```

The dependency does no longer seem needed, so just drop it.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>