mesa: Remove mesa GL headers to use vivante GL
Both mesa and imx-gpu-viv tries to install headers in the same
shared area and causes build break.

This fix is required to avoid the below error:
ERROR: The recipe imx-gpu-viv is trying to install files into a shared
area when those files already exist.

Signed-off-by: Neena Busireddy <neena.busireddy@freescale.com>