imx-gst1.0-plugin: Remove imx-opencl-converter for i.MX 8MNUL
The 8MNUL has no GPU, but imx-opencl-converter requires it.
Fixes:
```
| ../imx-opencl-converter-0.1/src/ocl.c:23:10: fatal error: CL/cl_ext_viv.h: No such file or directory
|    23 | #include <CL/cl_ext_viv.h>
|       |          ^~~~~~~~~~~~~~~~~
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>