pyarmnn: Add a temporary workaround to fix build break
pyarmnn is broken with following error:

ERROR: pyarmnn-20.02-r0 do_package_qa: QA Issue: /usr/lib/python3.8/site-packages/pyarmnn/_generated/_pyarmnn_version.cpython-37m-aarch64-linux-gnu.so
contained in package pyarmnn requires libpython3.7m.so.1.0()(64bit), but no providers found in RDEPENDS_pyarmnn? [file-rdeps]
ERROR: pyarmnn-20.02-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>