python3-wheel: Remove the bbappend temporarily
python3-wheel recipe is deleted from meta-openembedded and it will be moved to oe-core (poky)
Remove the bbappend temporarily until the main recipe is added in poky to get pass build errors.

https://github.com/openembedded/meta-openembedded/commit/c720dc971befa080f489d5bcf27eb50a0bb37031

This fixes the following error:

ERROR: No recipes in default available for:
  /home/nxa07886/kirkstone/sources/meta-imx/meta-sdk/dynamic-layers/openembedded-layer/recipes-devtools/python/python3-wheel_%.bbappend

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>