litert: Replace moving tag reference with fixed commit SHA
Replace the tag reference with a fixed commit ID. Tags can be moved, which caused parser failures when resolving revisions. Using an immutable commit SHA ensures reproducible offline builds and avoids issues in environments without network access.
When trying to run a build having the sources already in downloads directory but no network will get this error:
ERROR: ExpansionError during parsing /home/bambo/imx-yocto-bsp/sources/meta-imx/meta-imx-ml/recipes-libraries/litert/litert_2.1.0.bb
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered ethrough BB_NO_NETWORK (or set indirectly due to use of BB_FETCH_PREMIRRORONLY) but access requested with command git -c gc.autoDetach=false -c core.pager=cat eName=origin ls-remote https://github.com/abseil/abseil-cpp (for url https://github.com/abseil/abseil-cpp)
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]
Signed-off-by: Alexandra Safta <alexandra-ioana.safta@nxp.com>