layer.conf: Mask the meta-freescale-3rdparty recipes temporarily
Some packages in the meta-freescale got upgraded which broke meta-freescale-3rdparty bbapends.
MASK those recipes to fix parse error.

ERROR: No recipes in default available for:
  /home/bamboo/build/5.15-honister-full/fsl-imx-internal-wayland/yocto/sources/meta-freescale-3rdparty/recipes-bsp/atf/qoriq-atf_1.5.bbappend
  /home/bamboo/build/5.15-honister-full/fsl-imx-internal-wayland/yocto/sources/meta-freescale-3rdparty/recipes-kernel/linux/linux-qoriq_5.4.bbappend

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>