imx8qxpc0mek.conf: Fix initramfs build [YOCIMX-7140]
For the following build:
```
MACHINE=imx8qxpc0mek bitbake fsl-image-mfgtool-initramfs
```

There is a failure:
```
u-boot-imx-mfgtool PROVIDES u-boot-mfgtool but was skipped: The selected UBOOT_CONFIG key ['mfgtool'] has no match in dict_keys(['sd', 'fspi']).
u-boot-fslc-mfgtool PROVIDES u-boot-mfgtool but was skipped: The selected UBOOT_CONFIG key ['mfgtool'] has no match in dict_keys(['sd', 'fspi']).
u-boot-imx-mfgtool PROVIDES u-boot-mfgtool but was skipped: The selected UBOOT_CONFIG key ['mfgtool'] has no match in dict_keys(['sd', 'fspi']).
ERROR: Required build target 'fsl-image-mfgtool-initramfs' has no buildable providers.
Missing or unbuildable dependency chain was: ['fsl-image-mfgtool-initramfs', 'u-boot-mfgtool']
```

The problem is `UBOOT_CONFIG[mfgtool]` is not defined for the machine.

Note that upstream does no longer require this.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>