layer.conf: Fix build break for v35 EULA
The build is broken:

```
ERROR: imx-gpu-g2d-6.4.3.p4.4-r0 do_unpack: A valid package EULA with md5sum in ['01ba08a2b77c3a0a9d0ab5d4d83fed64', '3880bb9c943b135a30fad5e8aabd3ee9', 'a31dce3023402a821cfcdc1bb8dbdbc0', '8cf95184c220e247b9917e7244124c5a', '102094e9e695888c6a9f9fda9004165d', 'd4f548f93b5fe0ee2bc86758c344412d', 'be67a88e9e6c841043b005ad7bcf8309', '88595f92466edd79be7f4f9547ffa0ef', '6b552f505eedab4a11ab538cf3db743a', '08fd295cce89b0a9c74b9b83ed74f671', '6bd2df2910a2234bf6f419b7d2f531a3', '75abe2fa1d16ca79f87cde926f05f72d', 'ab61cab9599935bfe9f700405ef00f28', '5ab1a30d0cd181e3408077727ea5a2db', '6dfb32a488e5fd6bae52fbf6c7ebb086', '80c0478f4339af024519b3723023fe28', 'fb0303e4ee8b0e71c094171e2272bd44', '72c0f70181bb6e83eee6aab8de12a9f3', '6c12031a11b81db21cdfe0be88cac4b3', 'fd4b227530cd88a82af6a5982cfb724d', '228c72f2a91452b8a03c4cab30f30ef9', '1b4db4b25c3a1e422c0c0ed64feb65d2', '983e4c77621568488dd902b27e0c2143', 'e9e880185bda059c90c541d40ceca922', 'cf3f9b8d09bc3926b1004ea71f7a248a', '231e11849a4331fcbb19d7f4aab4a659', 'a632fefd1c359980434f9389833cab3a', '3c3fe2b904fd694f28d2f646ee16dddb', '85d06b38f17b935ca11784d67075b846', '417b82f17fc02b88125331ed312f6f1b', 'b3b0bab6ff55420d043cf1652c52d788', 'f35df765ff17e69043ea21f350e3229c', 'e565271ec9a80ce47abbddc4bffe56fa', '28241cb895217d7946e40e7227136d02', '03bcadc8dc0a788f66ca9e2b89f56c6f', 'dedee5689786754f61ea3a76035c8a81', '17d2319de7baa686e8a755ba58a9ebf5', 'e4098ac4459cb81b07d3f0c22b3e8370', 'be5ff43682ed6c57dfcbeb97651c2829', 'e565271ec9a80ce47abbddc4bffe56fa', '28241cb895217d7946e40e7227136d02', '03bcadc8dc0a788f66ca9e2b89f56c6f', 'dedee5689786754f61ea3a76035c8a81', '17d2319de7baa686e8a755ba58a9ebf5', 'e4098ac4459cb81b07d3f0c22b3e8370', 'be5ff43682ed6c57dfcbeb97651c2829', 'd3c315c6eaa43e07d8c130dc3a04a011'] was not found in LIC_FILES_CHKSUM 'file://COPYING;md5=d0122773a9d62bd492c87ffaf42463b5 file:///home/bamboo/automation/trunk_pkg_kirkstone/fsl-imx-internal-fb-qtwebengine/arm/yocto/sources/meta-imx/meta-bsp/../EULA.txt;md5=d3c315c6eaa43e07d8c130dc3a04a011'.
```

This is because the v35 EULA is changed, but the recipes still have the old
v35 checksum. Adding the old checksum to the list of valid EULAs fixes the
problem.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>