mesa: Disable Vulkan for 8M Mini [YOCIMX-6633]
The qt3d build is failing for 8M Mini:
```
| In file included from src/plugins/renderers/rhi/graphicshelpers/submissioncontext.cpp:57:
| /usr/include/QtGui/6.4.1/QtGui/private/qrhivulkan_p.h:36:5: error: 'VkPhysicalDevice' does not name a type
|    36 |     VkPhysicalDevice physDev = VK_NULL_HANDLE;
|       |     ^~~~~~~~~~~~~~~~
```

Vulkan support is dynamically configured for qt3d because mesa is
configured for Vulkan.

Since 8M Mini doesn't support Vulkan, disable vulkan in mesa, which disables
Vulkan in qt3d and avoids the build break.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>