distro: Add opencl to distro features
The imx-image-core build is broken:
```
ERROR: Nothing RPROVIDES 'clinfo' (but /.../meta-imx/meta-imx-sdk/recipes-fsl/images/imx-image-core.bb RDEPENDS on or otherwise requires it)
clinfo was skipped: missing required distro feature 'opencl' (not in DISTRO_FEATURES)
```

Add the distro feature opencl, new to Whinlatter.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>