plug-and-trust-ecc: Fix LIC_FILES_CHKSUM issue
License has been renamed from Apache_2_0.txt to LICENSE.txt

https://github.com/NXP/plug-and-trust/commit/92d003642bc154c025cf7e9ab011cac08c1de54b

Fixes the following error:
ERROR: plug-and-trust-ecc-4.4.0-r0 do_populate_lic: QA Issue: plug-and-trust-ecc: LIC_FILES_CHKSUM points to an invalid file

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>
(cherry picked from commit fda364c8c15a33c8a4515b87d99c4a486440b7ba)
Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>