directfb: Add patch from poky fido
bashism patch has been added in poky fido and needs to be included
in our layer else directfb fetch fails with following error:

ERROR: Fetcher failure: Unable to find file file://bashism.patch anywhere.

Signed-off-by: Neena Busireddy <neena.busireddy@freescale.com>