openglcts: Install missing data [YOCIMX-4445]
Add more data folders to the install, needed by the tests. Fixes the error:

```
FATAL ERROR: Failed to open file: './gles2/shaders/preprocessor.test' at tcuResource.cpp:53
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>