u-boot-imx: Use native version of Python instead of host version
After performing a host install of pip3 and typing
(for demo framework), this build started failing:

gcc  -isystem/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/usr/include -O2 -pipe -L/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/usr/lib -L/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/lib -Wl,-rpath-link,/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/usr/lib -Wl,-rpath-link,/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/lib -Wl,-rpath,/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/usr/lib -Wl,-rpath,/home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-internal-fb/temp_build_dir/build_fsl-imx-internal-fb/tmp/sysroots/x86_64-linux/lib -Wl,-O1  -o tools/mkimage tools/aisimage.o tools/atmelimage.o tools/common/bootm.o tools/lib/crc32.o tools/default_image.o tools/lib/fdtdec_common.o tools/lib/fdtdec.o tools/fit_common.o tools/fit_image.o tools/common/image-fit.o tools/image-host.o tools/common/image.o tools/imagetool.o tools/imximage.o tools/kwbimage.o tools/lib/md5.o tools/lpc32xximage.o tools/mxsimage.o tools/omapimage.o tools/os_support.o tools/pblimage.o tools/pbl_crc32.o tools/vybridimage.o tools/lib/rc4.o tools/rkcommon.o tools/rkimage.o tools/rksd.o tools/rkspi.o tools/socfpgaimage.o tools/lib/sha1.o tools/lib/sha256.o tools/common/hash.o tools/ublimage.o tools/zynqimage.o tools/zynqmpimage.o tools/lib/libfdt/fdt.o tools/lib/libfdt/fdt_ro.o tools/lib/libfdt/fdt_rw.o tools/lib/libfdt/fdt_strerror.o tools/lib/libfdt/fdt_wip.o tools/lib/libfdt/fdt_region.o tools/lib/libfdt/fdt_sw.o tools/gpimage.o tools/gpimage-common.o tools/mkimage.o
ERROR: oe_runmake failed
tools/libfdt_wrap.c:147:21: fatal error: Python.h: No such file or directory
  # include <Python.h>
                     ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

The Yocto sysroots had no missing /usr/include/python*/Python.h.
However, the build machine did have /usr/include/python2.7/Python.h
missing.

Fix the problem by using the Yocto native version of Python.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>