u-boot-imx: Update to commit 44898b9f3c
8MN and 8MP are broken after update to 02269be6a1:
```
| /home/bamboo/IMXYOCTO-BOOT-IMN-754/yocto/build/tmp/work/imx8mn_ddr4_evk-poky-linux/u-boot-imx/2025.04/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/14.3.0/ld: /tmp/ccHru0cb.ltrans8.ltrans.o: in function `imx_rproc_mmio_start':
| /usr/src/debug/u-boot-imx/2025.04/drivers/remoteproc/imx_rproc.c:80:(.text.imx_rproc_mmio_start+0x14): undefined reference to `regmap_update_bits'
| /home/bamboo/IMXYOCTO-BOOT-IMN-754/yocto/build/tmp/work/imx8mn_ddr4_evk-poky-linux/u-boot-imx/2025.04/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/14.3.0/ld: /tmp/ccHru0cb.ltrans8.ltrans.o: in function `imx_rproc_mmio_stop':
| /usr/src/debug/u-boot-imx/2025.04/drivers/remoteproc/imx_rproc.c:149:(.text.imx_rproc_mmio_stop+0x14): undefined reference to `regmap_update_bits'
| /home/bamboo/IMXYOCTO-BOOT-IMN-754/yocto/build/tmp/work/imx8mn_ddr4_evk-poky-linux/u-boot-imx/2025.04/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/14.3.0/ld: /tmp/ccHru0cb.ltrans8.ltrans.o: in function `imx_rproc_mmio_is_running':
| /usr/src/debug/u-boot-imx/2025.04/drivers/remoteproc/imx_rproc.c:197:(.text.imx_rproc_mmio_is_running+0x28): undefined reference to `regmap_read'
| /home/bamboo/IMXYOCTO-BOOT-IMN-754/yocto/build/tmp/work/imx8mn_ddr4_evk-poky-linux/u-boot-imx/2025.04/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/14.3.0/ld: /tmp/ccHru0cb.ltrans8.ltrans.o: in function `imx_rproc_probe':
| /usr/src/debug/u-boot-imx/2025.04/drivers/remoteproc/imx_rproc.c:312:(.text.imx_rproc_probe+0x50): undefined reference to `syscon_regmap_lookup_by_phandle'
| collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
```

Revert "u-boot-imx: Update to commit 02269be6a1"

This reverts commit 3e16f6463a91ffed92a01788041d18997c11b0f8.