wxwidgets: Revert PACKAGECONFIG change
The upstream recipe fails to build without x11 in DISTRO_FEATURES:

ERROR: //meta-openembedded/meta-oe/recipes-extended/wxwidgets/wxwidgets_3.1.5.bb: wxwidgets: PACKAGECONFIG[no_gui] Conflict package config 'opengl' set in PACKAGECONFIG.

Revert the recent change to the PACKAGECONFIG to fix the build.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>