ecdsa-lib-imx: Fix missing openssl dependency
Packages that depend on ecdsa-lib-imx fail to build with undefined
references like the following:

libECDSA.so.2.0: undefined reference to `EVP_MD_CTX_free@OPENSSL_1_1_0'

This is because the recipe is missing a dependency on openssl.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>