imx-gpu-apitrace: Fix ParseError due to infinite recursion
The version 10.0.0 recipe in meta-imx attempts to include the version
10.0.0 recipe in meta-freescale. Perhaps depending on the layer priority,
this does unfortunately set up the possibility of including itself and
thus an infinite recursion:
```
WARNING: /.../meta-imx/meta-bsp/recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_10.0.0.bb: Duplicate inclusion for /.../meta-imx/meta-bsp/recipes-graphic /.../meta-imx/meta-bsp/recipes-graphics/imx-gpu-apitrace/imx-gpu-apitrace_10.0.0.bb
[WARNING repeats numerous times]
ERROR: ParseError in None: Not all recipes parsed, parser thread killed/died? Exiting.######################################################################################################
ERROR: Parsing halted due to errors, see error messages above
```

Fix the problem by copying the upstream recipe.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>