qtmultimedia: Fix missing libxrandr dependency [YOCIMX-7429]
Fixes:
```
| src/plugins/multimedia/ffmpeg/qx11surfacecapture.cpp:21:10: fatal error: X11/extensions/Xrandr.h: No such file or directory
|    21 | #include <X11/extensions/Xrandr.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit a38cc3e9c78cb7e45ca655c6dbd77bde32878daf)