u-boot-imx: Add missing python dependency [YOCIMX-1828]
Saw the following error:

error: invalid Python installation: unable to open /home/bamboo/build/4.9.51-mx8_beta1/fsl-imx-xwayland/temp_build_dir/build_fsl-imx-xwayland/tmp/sysroots/imx8qmlpddr4arm2/usr/lib/python2.7/config/Makefile (No such file or directory)

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>