gstreamer1.0-plugins-base: Revert the temporary fix about header not found [YOCIMX-3575]
fatal error: xdg-shell-client-protocol.h: No such file or directory

This file is under build directory, which is not added into include dir.

The fix has been added into source code, no need to hold the fix in recipe anymore

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>