tinycompress: Fix the fetch issue
alsa userspace is now moved to github.
https://github.com/alsa-project/tinycompress/commit/ab91fdfe4e4cdabf6da073947b6485404ae06cc2

This fixes the following error:

ERROR: tinycompress-1.1.6-r0 do_fetch: Fetcher failure for URL: 'git://git.alsa-project.org/tinycompress.git;protocol=git;branch=master'.
Unable to fetch URL from any source

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>