packagegroup-qt6-imx: Drop meta-nxp-demo-experience if no x11 [MICRSE-1503]
The Smart Kitchen demo does require x11, so drop
meta-nxp-demo-experience to fix the build break:
```
ERROR: Nothing PROVIDES 'xdg-utils' (but sources/meta-nxp-demo-experience/recipes-nxp-demo-experience/demos/demo-experience-smart-kitchen.bb DEPENDS on or otherwise requires it)
xdg-utils was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
ERROR: Required build target 'test-internal-qt6' has no buildable providers.
Missing or unbuildable dependency chain was: ['test-internal-qt6', 'packagegroup-qt6-imx', 'nxp-demo-experience', 'demo-experience-smart-kitchen', 'xdg-utils']
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>
(cherry picked from commit 2c46e9bc8cb33eedcf4223e49ad06804a12addad)