imx-base-extend.inc: Use imx-boot recipe for 8MNUL [YOCIMX-6933]
The image task `do_image_wic` is failing for i.MX 8MNUL EVK:
```
FileNotFoundError: [Errno 2] No such file or directory: 'build/tmp/deploy/images/imx8mnul-ddr3l-evk/imx-boot'
```

The problem is the upstream machine configuration is choosing
the class `imx-boot-container` for the boot container mechanism,
not the recipe `imx-boot`.

Since we always want `imx-boot`, we can work around the issue for
now by just setting the flag ourself. The problem is currently
being addressed upstream via some rework:

https://github.com/Freescale/meta-freescale/pull/1465

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>