chromium-ozone-wayland: Fix build break [YOCIMX-4154]
Error:
| ../../third_party/webrtc/rtc_base/physical_socket_server.cc:73:27:
error: 'SIOCGSTAMP' was not declared in this scope; did you mean 'SIOCGRARP'?

SIOCGSTAMP is defined in linux/sockios.h since kernel 5.2.
Include that file wherever needed

Signed-off-by: Yuqing Zhu <carol.zhu@nxp.com>