wayland-ivi-extension: Add a workaround to fix build breaks
/usr/src/debug/wayland-ivi-extension/git-r0/git/ivi-layermanagement-api/ilmClient/include/ilm_client_platform.h:38: multiple definition of `gIlmClientPlatformFunc

GCC 10 defaults to -fno-common, which means a linker error will now be reported. In previous GCC versions this error is ignored

https://gcc.gnu.org/gcc-10/porting_to.html

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>