imx-base.inc: Use IMAGE_INSTALL to add optee, xen, and jailhouse [YOCIMX-3665]
Undo the change to use MACHINE_EXTRA_RRECOMMENDS instead of IMAGE_INSTALL.
It was a mistake and was causing a build break for core-image-minimal:

ERROR: _exec_cmd: install -m 0644 -D /home/nxf07554/Yocto/imx-warrior/build.github_6ul/tmp/deploy/images/imx6ulevk/tee.bin /home/nxf07554/Yocto/imx-warrior/build.github_6ul/tmp/work/imx6ulevk-poky-linux-gnueabi/core-image-minimal/1.0-r0/deploy-core-image-minimal-image-complete/core-image-minimal-imx6ulevk-20190710082045/tmp.wic.5eqg70p5/boot.2/tee.bin returned '1' instead of 0| output: install: cannot stat '/home/nxf07554/Yocto/imx-warrior/build.github_6ul/tmp/deploy/images/imx6ulevk/tee.bin': No such file or directory

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>