imx-g2d-samples: Fix build break
/bin/sh: 1: pkg-config: not found
| make[1]: Leaving directory '/home/nxa07886/kirkstone/bld-mx8/tmp/work/cortexa72-cortexa53-crypto-mx8-poky-linux/imx-g2d-samples/2.0.0-r0/git/overlay_test'
| /home/kirkstone/bld-mx8/tmp/work/cortexa72-cortexa53-crypto-mx8-poky-linux/imx-g2d-samples/2.0.0-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/
aarch64-poky-linux/gcc/aarch64-poky-linux/11.2.0/ld: g2d_wayland_cf.o: undefined reference to symbol 'wl_shell_surface_interface'
| /home/kirkstone/bld-mx8/tmp/work/cortexa72-cortexa53-crypto-mx8-poky-linux/imx-g2d-samples/2.0.0-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/
aarch64-poky-linux/gcc/aarch64-poky-linux/11.2.0/ld: /home/nxa07886/kirkstone/bld-mx8/tmp/work/cortexa72-cortexa53-crypto-mx8-poky-linux/imx-g2d-samples/2.0.0-r0/recipe-sysroot/usr/lib/libwayland-server.so.0: error adding symbols: DSO missing from command line
| collect2: error: ld returned 1 exit status
| Makefile:27: recipe for target 'g2d_wayland_cf_test' failed
| make[1]: *** [g2d_wayland_cf_test] Error 1

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>