opencv: Fix build error for getVar() expansion [YOCIMX-1075]
The package task was failing:

Exception: TypeError: getVar() missing 1 required positional argument: 'expand'

On poky master (pyro), DataSmart.getVar() was changed to expand by default.
The opencv recipe, also from master (pyro), was written to use the default,
and so was failing on our morty-based build.

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>