opencv: Disable cvv module in opencv_contrib as it is not yet suppported for Qt6 [YOCIMX-6355]
This is a workaround to get pass the following build error:

/home/bamboo/build/5.15-kirkstone-regression/fsl-imx-internal-xwayland/mx8/yocto/build/tmp/work/armv8a-mx8-poky-linux/opencv/4.6.0.imx-r0/build/
modules/cvv/opencv_cvv_autogen/MXUWEOXILK/../../../../../contrib/modules/cvv/src/gui/call_tab.hpp:4:10: fatal error: QString: No such file or directory

There is a pull request to add Qt6 support in opencv_contrib repo but it is not merged yet.

https://github.com/opencv/opencv_contrib/pull/3285

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>