packagegroup-qt6-imx: Remove nxp-demo-experienc temporarily until build breaks are fixed [YOCIMX-7311]
Error: demo-experience-imx-voiceui-smart-kitchen-1.0-r0 do_patch:
   Applying patch '0001-changed-BUILD_ARCH-CortexA55.patch'

This reverts commit 27127aeeedadb4f74d60867cc1c77541a096dc28.