packagegroup-imx-isp: Disable 8MP support due to build break [LF-12179]
```
ERROR: isp-imx-4.2.2.24.2-r0 do_package_qa: QA Issue: /usr/lib/libcam_device.so contained in package isp-imx requires libtinyxml2.so.9()(64bit), but no providers found in RDEPENDS:isp-imx? [file-rdeps]
```

Signed-off-by: Tom Hochstein <tom.hochstein@oss.nxp.com>