arm-compute-library: Fix build for 32-bit [YOCIMX-3119]
Turns out the compiler prefix patching done in the recipe was
not correct. For 64-bit it luckily had no effect. For 32-bit
it caused the following build error:

ERROR: Compiler ' arm-poky-linux-gnueabi-arm-poky-linux-gnueabi-g++  -march=armv7-a -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed --sysroot=/home/bamboo/build/4.14-sumo-regression/fsl-imx-internal-xwayland/mx6/temp_build_dir/build_fsl-imx-internal-xwayland/tmp/work/cortexa9hf-neon-poky-linux-gnueabi/arm-compute-library/18.11+gitAUTOINC+64441b79b8-r0/recipe-sysroot' not found

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>