minizip: Downgrade to 1.3.1
Upstream has upgraded minizip to 1.3.2 version and it broke Qtwebengine.
Downgrade it temporarily until the issue is fixed.

../../../../../sources/qtwebengine-6.11.0/src/3rdparty/chromium/third_party/zlib/google/zip_internal.cc:5:
build	13-Apr-2026 02:21:57	| ../../../../../recipe-sysroot/usr/include/minizip/ioapi.h:74:10: fatal error: ints.h: No such file or directory
build	13-Apr-2026 02:21:57	|    74 | #include "ints.h"

Signed-off-by: Neena Busireddy <neenareddy.busireddy@nxp.com>