el2go-agent: Fix multilib install [YOCIMX-9122]
The cmake files are hard-coded to install to lib, and thus will fail for
a multilib build, signaled by Yocto with a QA error.
```
ERROR: el2go-agent-6.3.0+git-r0 do_package: QA Issue: el2go-agent: Files/directories were installed but not shipped in any package:
  /usr/lib/libnxp_iot_agent.so
  /usr/lib/libnxp_iot_agent_common.so.6
  /usr/lib/libnxp_iot_agent_common.so.6.3.0
  /usr/lib/libnxp_iot_agent.so.6.3.0
  /usr/lib/libnxp_iot_agent_common.so
  /usr/lib/libnxp_iot_agent.so.6
  /usr/lib/cmake
  /usr/lib/cmake/el2go_agent
  /usr/lib/cmake/el2go_agent/el2go_agent-targets-noconfig.cmake
  /usr/lib/cmake/el2go_agent/el2go_agent-config.cmake
  /usr/lib/cmake/el2go_agent/el2go_agent-targets.cmake
  /usr/lib/cmake/el2go_agent/el2go_agent-config-version.cmake
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
el2go-agent: 12 installed and not shipped files. [installed-vs-shipped]
```

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>